import type { BrandIdentity } from '../../types.js';

export function exportSassVariables(brand: BrandIdentity): string {
  const { colors, typography, spacing } = brand;
  const lines: string[] = ['// Brand Identity - Generated by @forgespace/branding-mcp', ''];

  lines.push('// Colors');
  lines.push(`$color-primary: ${colors.primary.hex};`);
  lines.push(`$color-secondary: ${colors.secondary.hex};`);
  lines.push(`$color-accent: ${colors.accent.hex};`);
  for (const n of colors.neutral) {
    lines.push(`$color-${n.name}: ${n.hex};`);
  }
  lines.push(`$color-success: ${colors.semantic.success.hex};`);
  lines.push(`$color-warning: ${colors.semantic.warning.hex};`);
  lines.push(`$color-error: ${colors.semantic.error.hex};`);
  lines.push(`$color-info: ${colors.semantic.info.hex};`);
  lines.push('');

  lines.push('// Typography');
  lines.push(`$font-heading: '${typography.headingFont}', sans-serif;`);
  lines.push(`$font-body: '${typography.bodyFont}', sans-serif;`);
  lines.push(`$font-mono: '${typography.monoFont}', monospace;`);
  for (const step of typography.steps) {
    lines.push(`$text-${step.name}: ${step.size};`);
    lines.push(`$leading-${step.name}: ${step.lineHeight};`);
  }
  lines.push('');

  lines.push('// Spacing');
  for (const [key, value] of Object.entries(spacing.values)) {
    lines.push(`$spacing-${key}: ${value};`);
  }

  if (brand.shadows) {
    lines.push('');
    lines.push('// Shadows');
    for (const [name, level] of Object.entries(brand.shadows.levels)) {
      lines.push(`$shadow-${name}: ${level.cssValue};`);
    }
  }

  if (brand.borders) {
    lines.push('');
    lines.push('// Borders');
    for (const [name, value] of Object.entries(brand.borders.radii)) {
      lines.push(`$radius-${name}: ${value};`);
    }
    for (const [name, value] of Object.entries(brand.borders.widths)) {
      lines.push(`$border-${name}: ${value};`);
    }
  }

  if (brand.motion) {
    lines.push('');
    lines.push('// Motion');
    for (const [name, value] of Object.entries(brand.motion.durations)) {
      lines.push(`$duration-${name}: ${value};`);
    }
    for (const [name, value] of Object.entries(brand.motion.easings)) {
      lines.push(`$ease-${name}: ${value};`);
    }
  }

  return lines.join('\n') + '\n';
}
