import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { brandDocFormatSchema } from '../lib/branding-core/validators/token-schema.js';
import type { BrandIdentity } from '../lib/types.js';
import { logger } from '../lib/logger.js';

function generateHtmlGuidelines(brand: BrandIdentity): string {
  const { colors, typography } = brand;
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${brand.name} - Brand Guidelines</title>
  <style>
    body { font-family: '${typography.bodyFont}', sans-serif; max-width: 960px; margin: 0 auto; padding: 2rem; color: #1a1a1a; }
    h1, h2, h3 { font-family: '${typography.headingFont}', sans-serif; }
    .swatch { display: inline-block; width: 80px; height: 80px; border-radius: 8px; margin: 4px; }
    .color-label { font-size: 12px; text-align: center; margin-top: 4px; }
    .section { margin: 2rem 0; padding: 1.5rem; border: 1px solid #e0e0e0; border-radius: 8px; }
  </style>
</head>
<body>
  <h1>${brand.name} Brand Guidelines</h1>
  ${brand.tagline ? `<p><em>${brand.tagline}</em></p>` : ''}

  <div class="section">
    <h2>Color Palette</h2>
    <div>
      <div><div class="swatch" style="background:${colors.primary.hex}"></div><div class="color-label">Primary<br>${colors.primary.hex}</div></div>
      <div><div class="swatch" style="background:${colors.secondary.hex}"></div><div class="color-label">Secondary<br>${colors.secondary.hex}</div></div>
      <div><div class="swatch" style="background:${colors.accent.hex}"></div><div class="color-label">Accent<br>${colors.accent.hex}</div></div>
    </div>
    <h3>Neutrals</h3>
    <div>${colors.neutral.map((n) => `<div style="display:inline-block"><div class="swatch" style="background:${n.hex}"></div><div class="color-label">${n.name}<br>${n.hex}</div></div>`).join('')}</div>
  </div>

  <div class="section">
    <h2>Typography</h2>
    <p><strong>Heading:</strong> ${typography.headingFont}</p>
    <p><strong>Body:</strong> ${typography.bodyFont}</p>
    <p><strong>Mono:</strong> ${typography.monoFont}</p>
    <h3>Type Scale</h3>
    ${typography.steps.map((s) => `<p style="font-size:${s.size};line-height:${s.lineHeight};font-weight:${s.weight}">${s.name} — ${s.size}</p>`).join('\n    ')}
  </div>

  <div class="section">
    <h2>Logo</h2>
    ${brand.logo?.svg ? brand.logo.svg : '<p>Logo not generated</p>'}
  </div>

  <footer><p>Generated by @forgespace/branding-mcp</p></footer>
</body>
</html>`;
}

export function registerCreateBrandGuidelines(server: McpServer): void {
  server.tool(
    'create_brand_guidelines',
    'Generate a brand guidelines document (HTML brand book) from a brand identity. Includes color swatches, typography samples, logo, and usage rules.',
    {
      brand: z.string().describe('Full BrandIdentity JSON'),
      format: brandDocFormatSchema.optional().describe('Output format (html supported)'),
    },
    async ({ brand, format }) => {
      try {
        logger.info({ format }, 'Creating brand guidelines');
        const brandData: BrandIdentity = JSON.parse(brand);

        if (format === 'pdf') {
          return {
            content: [
              {
                type: 'text',
                text: 'PDF generation requires pdfkit. Use HTML format or install optional dependencies.',
              },
            ],
          };
        }

        const html = generateHtmlGuidelines(brandData);
        return {
          content: [{ type: 'text', text: html }],
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: 'text', text: `Error creating guidelines: ${message}` }],
          isError: true,
        };
      }
    }
  );
}
